// import localFont from "next/font/local";
// import "./globals.css";
// import { ChakraProvider } from '@chakra-ui/react';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <ChakraProvider theme={theme}>
//           {children}
//         </ChakraProvider>
//       </body>
//     </html>
//   );
// }
import { ThemeProvider, CssBaseline } from '@mui/material';
import { createTheme } from '@mui/material/styles';
// import customTheme from '../theme';  // Optional: If using a custom theme

// You can define a custom theme or use the default theme
const customTheme = createTheme({
  palette: {
    primary: {
      main: '#1976d2',  // Custom primary color
    },
    secondary: {
      main: '#dc004e',  // Custom secondary color
    },
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={customTheme}>  {/* Wrap app with ThemeProvider */}
          <CssBaseline />  {/* Normalize styles and apply baseline styles */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
